SOS21GB/LostMyLighter4

LostMyLighterGroup4/CreateAddress.cs
Prova gärna AddPostCode() med alla alternativ ni kan komma på.
=> Inmatningsmetoder påbörjade. AddPostCode klar (?).

LostMyLighterGroup4/ManagerClasses/ProgramManager.cs, LostMyLighterGroup4/MenuClasses/LoggedInMenu.cs
=> lagt till logga-ut alternativ

LostMyLighterGroup4/Marschall.cs
Skapade get-properties för samtliga fält ifall de behövs utanför. Inga set då konstruktorn tar in alla värden redan.
Inkluderade en liten fix i konstruktorn också.
Closes #46
=> Get-properties for fields in marschall class

LostMyLighterGroup4/Marschall.cs
La till en statisk lista för marschaller och en static public property för att komma åt listan utifrån (kan tas bort senare). 
Closes #58
=> static Marschall list och get för listan

LostMyLighterGroup4/AddressClass/Address.cs
=> ändrat postcode från int till string

LostMyLighterGroup4/Marschall.cs
=> Marschall sökfunktioner för postkod och gatnunamn

LostMyLighterGroup4/LogIn/LogIn.cs, LostMyLighterGroup4/ManagerClasses/ProgramManager.cs, LostMyLighterGroup4/MenuClasses/LoggedInMenu.cs, LostMyLighterGroup4/MenuClasses/StandardMenu.cs, LostMyLighterGroup4/Program.cs, LostMyLighterGroup4/user.cs
hade inte menu fix i denna från början, så nu är båda issuearna med i denna. Vet inte om vi ska göra båda pullsen isåfall...
closes #74 
closes #69
=> fixat möjlighet att avbryta inlogg, inkluderar menu fix

LostMyLighterGroup4/ManagerClasses/ProgramManager.cs, LostMyLighterGroup4/user.cs
fixat GetUserByID och snyggat till lite här och där i User, lagt in fungerande log in, visa profil och marshallmeny metoder i programmanagern, kommer inte så mycket längre utan att de sista klasserna är i bruk
closes #42
=> fixat i user, samt lagt till lite basic metoder i programManager

LostMyLighterGroup4/Marschall.cs
=> Fixat FindStreet-metoden

LostMyLighterGroup4/ManagerClasses/ProgramManager.cs, LostMyLighterGroup4/user.cs
samt lagt till lite UX till addlighter metoden
closes #94
=> kan registrera tändare från menyn.

LostMyLighterGroup4/user.cs
=> DeleteUser-metod. Generella fixar. Formatterat printinfo

LostMyLighterGroup4/CreateMarschall.cs, LostMyLighterGroup4/MenuClasses/LoggedInMenu.cs, LostMyLighterGroup4/MenuClasses/SearchMenu.cs, LostMyLighterGroup4/MenuClasses/StandardMenu.cs
Snyggat till utskriften.
CreateMarshall har tagit in adressobjektet och lite småjusteringar.
=> Justering i menyklasserna + createmarshall.

LostMyLighterGroup4/Userinput1.cs
=> fixade variablernas init värden

LostMyLighterGroup4/CreateMarschall.cs
Versionen som ställde till problem för mig.
=> Ändrat diverse.

LostMyLighterGroup4/Marschall.cs
=> Utskrift på svenska. Skriver ut postkod och stad nu

LostMyLighterGroup4/ManagerClasses/ProgramManager.cs, LostMyLighterGroup4/MenuClasses/LoggedInMenu.cs, LostMyLighterGroup4/MenuClasses/SearchMenu.cs, LostMyLighterGroup4/MenuClasses/StandardMenu.cs, LostMyLighterGroup4/Program.cs, LostMyLighterGroup4/user.cs
closes #19 
En hel del ändringar:
ta bort användare fungerar, har lagt till kontrollfråga så man inte råkar ta bort sin profil av misstag, samt ändrat som jag tycker med skärmrensning och tangenttrycksförfrågan (har säkert missat nånstans eller om ni har andra åsikter hur det ska se ut), committar program.cs också för jag är trött på att ta bort dummyusers och skapa ny user varje gång jag vill testa.
=> Delete user + tillsnyggningar

LostMyLighterGroup4/CreateAddress.cs, LostMyLighterGroup4/user.cs
=> Två småändringar bara i user och creataddress.

LostMyLighterGroup4/Marschall.cs
=> Rensat bland mina kommentarer.

LostMyLighterGroup4/ManagerClasses/ProgramManager.cs
=> Call metod till Creater user

LostMyLighterGroup4/Marschall.cs
=> Avbryta sökning med 0. Extra felcheck i husnummer och bokstav

LostMyLighterGroup4/ChangeUser.cs, LostMyLighterGroup4/CreateAddress.cs, LostMyLighterGroup4/ManagerClasses/ProgramManager.cs, LostMyLighterGroup4/Marschall.cs
Programmanager fixad helt? Småfixar till changeuser, createaddress, marschall
Closes #140 
Closes #156 
Closes #138
=> Programmanager + småfixar

LostMyLighterGroup4/ChangeUser.cs, LostMyLighterGroup4/LogIn/LogIn.cs, LostMyLighterGroup4/ManagerClasses/ProgramManager.cs, LostMyLighterGroup4/MenuClasses/LoggedInMenu.cs, LostMyLighterGroup4/MenuClasses/StandardMenu.cs
=> en massa helt nödvändiga ändringar.

LostMyLighterGroup4/CreateMarschall.cs, LostMyLighterGroup4/CreateUser.cs, LostMyLighterGroup4/Marschall.cs
Closes #166,closes #168 ,closes #174, closes #175
=> Justerat lite i tre klasser.

LostMyLighterGroup4/ManagerClasses/ProgramManager.cs
=> räknar upp antal marschaller

LostMyLighterGroup4/CreateMarschall.cs, LostMyLighterGroup4/ManagerClasses/ProgramManager.cs, LostMyLighterGroup4/Marschall.cs, LostMyLighterGroup4/MenuClasses/SearchMenu.cs, LostMyLighterGroup4/user.cs
fixat en massa textformateringar, lagt till user searchcount så att det fungerar samt skriver ut meddelande om det ej finns aktiva/registrerade marschaller
closes #177
=> massa bugfix

LostMyLighterGroup4/Marschall.cs
=> marschall print fixes

LostMyLighterGroup4/Marschall.cs
=> Formatering etc.

LostMyLighterGroup4/CreateUser.cs
=> fixat input check

LostMyLighterGroup4/MenuClasses/LoggedInMenu.cs, LostMyLighterGroup4/MenuClasses/StandardMenu.cs
=> Mindre menyjusteringar.
